/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as PrayerIndexRouteImport } from './routes/prayer/index'
import { Route as PodcastIndexRouteImport } from './routes/podcast/index'
import { Route as KidsIndexRouteImport } from './routes/kids/index'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources/$resourceId'
import { Route as PrayerVideoRouteImport } from './routes/prayer/video'
import { Route as PrayerDashboardRouteImport } from './routes/prayer/dashboard'
import { Route as KidsWatchRouteImport } from './routes/kids/watch'
import { Route as KidsTopicsRouteImport } from './routes/kids/topics'
import { Route as KidsSubscribeRouteImport } from './routes/kids/subscribe'
import { Route as KidsSeriesRouteImport } from './routes/kids/series'
import { Route as KidsLibraryRouteImport } from './routes/kids/library'
import { Route as FilmsWatchRouteImport } from './routes/films/watch'
import { Route as FilmsTrailerRouteImport } from './routes/films/trailer'
import { Route as FilmsFilmIdRouteImport } from './routes/films/$filmId'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminShopRouteImport } from './routes/admin/shop'
import { Route as AdminResourcesRouteImport } from './routes/admin/resources'
import { Route as AdminPrayerRouteImport } from './routes/admin/prayer'
import { Route as AdminPodcastRouteImport } from './routes/admin/podcast'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminKidsRouteImport } from './routes/admin/kids'
import { Route as AdminFilmsRouteImport } from './routes/admin/films'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDonationsRouteImport } from './routes/admin/donations'
import { Route as PrayerSeriesSeriesIdRouteImport } from './routes/prayer/series/$seriesId'
import { Route as PodcastSeasonSeasonIdRouteImport } from './routes/podcast/season/$seasonId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const PrayerIndexRoute = PrayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrayerRoute,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastRoute,
} as any)
const KidsIndexRoute = KidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRoute,
} as any)
const PrayerVideoRoute = PrayerVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => PrayerRoute,
} as any)
const PrayerDashboardRoute = PrayerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrayerRoute,
} as any)
const KidsWatchRoute = KidsWatchRouteImport.update({
  id: '/kids/watch',
  path: '/kids/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsTopicsRoute = KidsTopicsRouteImport.update({
  id: '/kids/topics',
  path: '/kids/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsSubscribeRoute = KidsSubscribeRouteImport.update({
  id: '/kids/subscribe',
  path: '/kids/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsSeriesRoute = KidsSeriesRouteImport.update({
  id: '/kids/series',
  path: '/kids/series',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLibraryRoute = KidsLibraryRouteImport.update({
  id: '/kids/library',
  path: '/kids/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsWatchRoute = FilmsWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmsTrailerRoute = FilmsTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => FilmsRoute,
} as any)
const FilmsFilmIdRoute = FilmsFilmIdRouteImport.update({
  id: '/$filmId',
  path: '/$filmId',
  getParentRoute: () => FilmsRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrayerRoute = AdminPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPodcastRoute = AdminPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKidsRoute = AdminKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilmsRoute = AdminFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const PrayerSeriesSeriesIdRoute = PrayerSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => PrayerRoute,
} as any)
const PodcastSeasonSeasonIdRoute = PodcastSeasonSeasonIdRouteImport.update({
  id: '/season/$seasonId',
  path: '/season/$seasonId',
  getParentRoute: () => PodcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/films': typeof AdminFilmsRoute
  '/admin/kids': typeof AdminKidsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/podcast': typeof AdminPodcastRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/trailer': typeof FilmsTrailerRoute
  '/films/watch': typeof FilmsWatchRoute
  '/kids/library': typeof KidsLibraryRoute
  '/kids/series': typeof KidsSeriesRoute
  '/kids/subscribe': typeof KidsSubscribeRoute
  '/kids/topics': typeof KidsTopicsRoute
  '/kids/watch': typeof KidsWatchRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/kids/': typeof KidsIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/prayer/': typeof PrayerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
  '/prayer/series/$seriesId': typeof PrayerSeriesSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/profile': typeof ProfileRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/films': typeof AdminFilmsRoute
  '/admin/kids': typeof AdminKidsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/podcast': typeof AdminPodcastRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/trailer': typeof FilmsTrailerRoute
  '/films/watch': typeof FilmsWatchRoute
  '/kids/library': typeof KidsLibraryRoute
  '/kids/series': typeof KidsSeriesRoute
  '/kids/subscribe': typeof KidsSubscribeRoute
  '/kids/topics': typeof KidsTopicsRoute
  '/kids/watch': typeof KidsWatchRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/contact': typeof ContactIndexRoute
  '/films': typeof FilmsIndexRoute
  '/kids': typeof KidsIndexRoute
  '/podcast': typeof PodcastIndexRoute
  '/prayer': typeof PrayerIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/support': typeof SupportIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
  '/prayer/series/$seriesId': typeof PrayerSeriesSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/films': typeof FilmsRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/films': typeof AdminFilmsRoute
  '/admin/kids': typeof AdminKidsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/podcast': typeof AdminPodcastRoute
  '/admin/prayer': typeof AdminPrayerRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/films/$filmId': typeof FilmsFilmIdRoute
  '/films/trailer': typeof FilmsTrailerRoute
  '/films/watch': typeof FilmsWatchRoute
  '/kids/library': typeof KidsLibraryRoute
  '/kids/series': typeof KidsSeriesRoute
  '/kids/subscribe': typeof KidsSubscribeRoute
  '/kids/topics': typeof KidsTopicsRoute
  '/kids/watch': typeof KidsWatchRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/kids/': typeof KidsIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/prayer/': typeof PrayerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/support/': typeof SupportIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
  '/prayer/series/$seriesId': typeof PrayerSeriesSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/cart'
    | '/events'
    | '/films'
    | '/login'
    | '/newsletter'
    | '/podcast'
    | '/prayer'
    | '/profile'
    | '/resources'
    | '/shop'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/films'
    | '/admin/kids'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/payments'
    | '/admin/podcast'
    | '/admin/prayer'
    | '/admin/resources'
    | '/admin/shop'
    | '/admin/users'
    | '/books/$bookId'
    | '/films/$filmId'
    | '/films/trailer'
    | '/films/watch'
    | '/kids/library'
    | '/kids/series'
    | '/kids/subscribe'
    | '/kids/topics'
    | '/kids/watch'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/about/'
    | '/admin/'
    | '/books/'
    | '/contact/'
    | '/films/'
    | '/kids/'
    | '/podcast/'
    | '/prayer/'
    | '/resources/'
    | '/shop/'
    | '/support/'
    | '/podcast/season/$seasonId'
    | '/prayer/series/$seriesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/events'
    | '/login'
    | '/newsletter'
    | '/profile'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/films'
    | '/admin/kids'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/payments'
    | '/admin/podcast'
    | '/admin/prayer'
    | '/admin/resources'
    | '/admin/shop'
    | '/admin/users'
    | '/books/$bookId'
    | '/films/$filmId'
    | '/films/trailer'
    | '/films/watch'
    | '/kids/library'
    | '/kids/series'
    | '/kids/subscribe'
    | '/kids/topics'
    | '/kids/watch'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/about'
    | '/admin'
    | '/books'
    | '/contact'
    | '/films'
    | '/kids'
    | '/podcast'
    | '/prayer'
    | '/resources'
    | '/shop'
    | '/support'
    | '/podcast/season/$seasonId'
    | '/prayer/series/$seriesId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/cart'
    | '/events'
    | '/films'
    | '/login'
    | '/newsletter'
    | '/podcast'
    | '/prayer'
    | '/profile'
    | '/resources'
    | '/shop'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/films'
    | '/admin/kids'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/payments'
    | '/admin/podcast'
    | '/admin/prayer'
    | '/admin/resources'
    | '/admin/shop'
    | '/admin/users'
    | '/books/$bookId'
    | '/films/$filmId'
    | '/films/trailer'
    | '/films/watch'
    | '/kids/library'
    | '/kids/series'
    | '/kids/subscribe'
    | '/kids/topics'
    | '/kids/watch'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/about/'
    | '/admin/'
    | '/books/'
    | '/contact/'
    | '/films/'
    | '/kids/'
    | '/podcast/'
    | '/prayer/'
    | '/resources/'
    | '/shop/'
    | '/support/'
    | '/podcast/season/$seasonId'
    | '/prayer/series/$seriesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  CartRoute: typeof CartRoute
  EventsRoute: typeof EventsRoute
  FilmsRoute: typeof FilmsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  PrayerRoute: typeof PrayerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  KidsLibraryRoute: typeof KidsLibraryRoute
  KidsSeriesRoute: typeof KidsSeriesRoute
  KidsSubscribeRoute: typeof KidsSubscribeRoute
  KidsTopicsRoute: typeof KidsTopicsRoute
  KidsWatchRoute: typeof KidsWatchRoute
  ContactIndexRoute: typeof ContactIndexRoute
  KidsIndexRoute: typeof KidsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/prayer/': {
      id: '/prayer/'
      path: '/'
      fullPath: '/prayer/'
      preLoaderRoute: typeof PrayerIndexRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/kids/': {
      id: '/kids/'
      path: '/kids'
      fullPath: '/kids/'
      preLoaderRoute: typeof KidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/prayer/video': {
      id: '/prayer/video'
      path: '/video'
      fullPath: '/prayer/video'
      preLoaderRoute: typeof PrayerVideoRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/prayer/dashboard': {
      id: '/prayer/dashboard'
      path: '/dashboard'
      fullPath: '/prayer/dashboard'
      preLoaderRoute: typeof PrayerDashboardRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/kids/watch': {
      id: '/kids/watch'
      path: '/kids/watch'
      fullPath: '/kids/watch'
      preLoaderRoute: typeof KidsWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/topics': {
      id: '/kids/topics'
      path: '/kids/topics'
      fullPath: '/kids/topics'
      preLoaderRoute: typeof KidsTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/subscribe': {
      id: '/kids/subscribe'
      path: '/kids/subscribe'
      fullPath: '/kids/subscribe'
      preLoaderRoute: typeof KidsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/series': {
      id: '/kids/series'
      path: '/kids/series'
      fullPath: '/kids/series'
      preLoaderRoute: typeof KidsSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/library': {
      id: '/kids/library'
      path: '/kids/library'
      fullPath: '/kids/library'
      preLoaderRoute: typeof KidsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/watch': {
      id: '/films/watch'
      path: '/watch'
      fullPath: '/films/watch'
      preLoaderRoute: typeof FilmsWatchRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/films/trailer': {
      id: '/films/trailer'
      path: '/trailer'
      fullPath: '/films/trailer'
      preLoaderRoute: typeof FilmsTrailerRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/films/$filmId': {
      id: '/films/$filmId'
      path: '/$filmId'
      fullPath: '/films/$filmId'
      preLoaderRoute: typeof FilmsFilmIdRouteImport
      parentRoute: typeof FilmsRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prayer': {
      id: '/admin/prayer'
      path: '/prayer'
      fullPath: '/admin/prayer'
      preLoaderRoute: typeof AdminPrayerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/podcast': {
      id: '/admin/podcast'
      path: '/podcast'
      fullPath: '/admin/podcast'
      preLoaderRoute: typeof AdminPodcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kids': {
      id: '/admin/kids'
      path: '/kids'
      fullPath: '/admin/kids'
      preLoaderRoute: typeof AdminKidsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/films': {
      id: '/admin/films'
      path: '/films'
      fullPath: '/admin/films'
      preLoaderRoute: typeof AdminFilmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prayer/series/$seriesId': {
      id: '/prayer/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/prayer/series/$seriesId'
      preLoaderRoute: typeof PrayerSeriesSeriesIdRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/podcast/season/$seasonId': {
      id: '/podcast/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/podcast/season/$seasonId'
      preLoaderRoute: typeof PodcastSeasonSeasonIdRouteImport
      parentRoute: typeof PodcastRoute
    }
  }
}

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AdminRouteChildren {
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFilmsRoute: typeof AdminFilmsRoute
  AdminKidsRoute: typeof AdminKidsRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPodcastRoute: typeof AdminPodcastRoute
  AdminPrayerRoute: typeof AdminPrayerRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFilmsRoute: AdminFilmsRoute,
  AdminKidsRoute: AdminKidsRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPodcastRoute: AdminPodcastRoute,
  AdminPrayerRoute: AdminPrayerRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminShopRoute: AdminShopRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface FilmsRouteChildren {
  FilmsFilmIdRoute: typeof FilmsFilmIdRoute
  FilmsTrailerRoute: typeof FilmsTrailerRoute
  FilmsWatchRoute: typeof FilmsWatchRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

const FilmsRouteChildren: FilmsRouteChildren = {
  FilmsFilmIdRoute: FilmsFilmIdRoute,
  FilmsTrailerRoute: FilmsTrailerRoute,
  FilmsWatchRoute: FilmsWatchRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}

const FilmsRouteWithChildren = FilmsRoute._addFileChildren(FilmsRouteChildren)

interface PodcastRouteChildren {
  PodcastIndexRoute: typeof PodcastIndexRoute
  PodcastSeasonSeasonIdRoute: typeof PodcastSeasonSeasonIdRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastIndexRoute: PodcastIndexRoute,
  PodcastSeasonSeasonIdRoute: PodcastSeasonSeasonIdRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface PrayerRouteChildren {
  PrayerDashboardRoute: typeof PrayerDashboardRoute
  PrayerVideoRoute: typeof PrayerVideoRoute
  PrayerIndexRoute: typeof PrayerIndexRoute
  PrayerSeriesSeriesIdRoute: typeof PrayerSeriesSeriesIdRoute
}

const PrayerRouteChildren: PrayerRouteChildren = {
  PrayerDashboardRoute: PrayerDashboardRoute,
  PrayerVideoRoute: PrayerVideoRoute,
  PrayerIndexRoute: PrayerIndexRoute,
  PrayerSeriesSeriesIdRoute: PrayerSeriesSeriesIdRoute,
}

const PrayerRouteWithChildren =
  PrayerRoute._addFileChildren(PrayerRouteChildren)

interface ResourcesRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  CartRoute: CartRoute,
  EventsRoute: EventsRoute,
  FilmsRoute: FilmsRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastRoute: PodcastRouteWithChildren,
  PrayerRoute: PrayerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  KidsLibraryRoute: KidsLibraryRoute,
  KidsSeriesRoute: KidsSeriesRoute,
  KidsSubscribeRoute: KidsSubscribeRoute,
  KidsTopicsRoute: KidsTopicsRoute,
  KidsWatchRoute: KidsWatchRoute,
  ContactIndexRoute: ContactIndexRoute,
  KidsIndexRoute: KidsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
