/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as PrayerIndexRouteImport } from './routes/prayer/index'
import { Route as PodcastIndexRouteImport } from './routes/podcast/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources/$resourceId'
import { Route as PrayerVideoRouteImport } from './routes/prayer/video'
import { Route as PrayerDashboardRouteImport } from './routes/prayer/dashboard'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as PodcastSeasonSeasonIdRouteImport } from './routes/podcast/season/$seasonId'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const PrayerIndexRoute = PrayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrayerRoute,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRoute,
} as any)
const PrayerVideoRoute = PrayerVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => PrayerRoute,
} as any)
const PrayerDashboardRoute = PrayerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrayerRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const PodcastSeasonSeasonIdRoute = PodcastSeasonSeasonIdRouteImport.update({
  id: '/season/$seasonId',
  path: '/season/$seasonId',
  getParentRoute: () => PodcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/events': typeof EventsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/prayer/': typeof PrayerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/books': typeof BooksIndexRoute
  '/podcast': typeof PodcastIndexRoute
  '/prayer': typeof PrayerIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/events': typeof EventsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/prayer/dashboard': typeof PrayerDashboardRoute
  '/prayer/video': typeof PrayerVideoRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/prayer/': typeof PrayerIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/events'
    | '/podcast'
    | '/prayer'
    | '/resources'
    | '/shop'
    | '/books/$bookId'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/books/'
    | '/podcast/'
    | '/prayer/'
    | '/resources/'
    | '/shop/'
    | '/podcast/season/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/books/$bookId'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/books'
    | '/podcast'
    | '/prayer'
    | '/resources'
    | '/shop'
    | '/podcast/season/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/events'
    | '/podcast'
    | '/prayer'
    | '/resources'
    | '/shop'
    | '/books/$bookId'
    | '/prayer/dashboard'
    | '/prayer/video'
    | '/resources/$resourceId'
    | '/shop/$productId'
    | '/books/'
    | '/podcast/'
    | '/prayer/'
    | '/resources/'
    | '/shop/'
    | '/podcast/season/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  EventsRoute: typeof EventsRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  PrayerRoute: typeof PrayerRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/prayer/': {
      id: '/prayer/'
      path: '/'
      fullPath: '/prayer/'
      preLoaderRoute: typeof PrayerIndexRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/prayer/video': {
      id: '/prayer/video'
      path: '/video'
      fullPath: '/prayer/video'
      preLoaderRoute: typeof PrayerVideoRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/prayer/dashboard': {
      id: '/prayer/dashboard'
      path: '/dashboard'
      fullPath: '/prayer/dashboard'
      preLoaderRoute: typeof PrayerDashboardRouteImport
      parentRoute: typeof PrayerRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/podcast/season/$seasonId': {
      id: '/podcast/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/podcast/season/$seasonId'
      preLoaderRoute: typeof PodcastSeasonSeasonIdRouteImport
      parentRoute: typeof PodcastRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface PodcastRouteChildren {
  PodcastIndexRoute: typeof PodcastIndexRoute
  PodcastSeasonSeasonIdRoute: typeof PodcastSeasonSeasonIdRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastIndexRoute: PodcastIndexRoute,
  PodcastSeasonSeasonIdRoute: PodcastSeasonSeasonIdRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface PrayerRouteChildren {
  PrayerDashboardRoute: typeof PrayerDashboardRoute
  PrayerVideoRoute: typeof PrayerVideoRoute
  PrayerIndexRoute: typeof PrayerIndexRoute
}

const PrayerRouteChildren: PrayerRouteChildren = {
  PrayerDashboardRoute: PrayerDashboardRoute,
  PrayerVideoRoute: PrayerVideoRoute,
  PrayerIndexRoute: PrayerIndexRoute,
}

const PrayerRouteWithChildren =
  PrayerRoute._addFileChildren(PrayerRouteChildren)

interface ResourcesRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  EventsRoute: EventsRoute,
  PodcastRoute: PodcastRouteWithChildren,
  PrayerRoute: PrayerRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
