/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastIndexRouteImport } from './routes/podcast/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as PodcastSeasonSeasonIdRouteImport } from './routes/podcast/season/$seasonId'

const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const PodcastSeasonSeasonIdRoute = PodcastSeasonSeasonIdRouteImport.update({
  id: '/season/$seasonId',
  path: '/season/$seasonId',
  getParentRoute: () => PodcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/events': typeof EventsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/prayer': typeof PrayerRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
  '/podcast': typeof PodcastIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/events': typeof EventsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/prayer': typeof PrayerRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/podcast/season/$seasonId': typeof PodcastSeasonSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/events'
    | '/podcast'
    | '/prayer'
    | '/books/$bookId'
    | '/books/'
    | '/podcast/'
    | '/podcast/season/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/prayer'
    | '/books/$bookId'
    | '/books'
    | '/podcast'
    | '/podcast/season/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/events'
    | '/podcast'
    | '/prayer'
    | '/books/$bookId'
    | '/books/'
    | '/podcast/'
    | '/podcast/season/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  EventsRoute: typeof EventsRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  PrayerRoute: typeof PrayerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/podcast/season/$seasonId': {
      id: '/podcast/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/podcast/season/$seasonId'
      preLoaderRoute: typeof PodcastSeasonSeasonIdRouteImport
      parentRoute: typeof PodcastRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface PodcastRouteChildren {
  PodcastIndexRoute: typeof PodcastIndexRoute
  PodcastSeasonSeasonIdRoute: typeof PodcastSeasonSeasonIdRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastIndexRoute: PodcastIndexRoute,
  PodcastSeasonSeasonIdRoute: PodcastSeasonSeasonIdRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  EventsRoute: EventsRoute,
  PodcastRoute: PodcastRouteWithChildren,
  PrayerRoute: PrayerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
